version: '3.7'

services:
  nginx:
    build:
      context: ./src/sysadmin
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/config/static
      - /var/log/nginx:/var/log/nginx
      - ./entrypoints/certbot/www:/var/www/certbot/:ro
      - ./entrypoints/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend
    networks:
      - sysadmin-network

  backend:
    build:
      context: ./src/sysadmin
      args:
        - PROJECT_ENVIRONMENT_TYPE=${PROJECT_ENVIRONMENT_TYPE}
    hostname: backend
    entrypoint: ./entrypoints/entrypoint.sh
    # restart: always
    volumes:
      - static_volume:/app/config/static
    env_file:
      - ./src/sysadmin/project.env/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.${PROJECT_ENVIRONMENT_TYPE}
    networks:
      - sysadmin-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./entrypoints/certbot/www/:/var/www/certbot/:rw
      - ./entrypoints/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - sysadmin-network

volumes:
  static_volume:

networks:
  sysadmin-network:
