version: '3.7'

services:
  nginx:
    build:
      context: ./src/sysadmin
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/app/config/static
    depends_on:
      - backend
    networks:
      - sysadmin-network

  backend:
    build:
      context: ./src/sysadmin
      args:
        - PROJECT_ENVIRONMENT_TYPE=${PROJECT_ENVIRONMENT_TYPE}
    hostname: backend
    entrypoint: ./entrypoints/entrypoint.sh
    # restart: always
    volumes:
      - static_volume:/app/config/static
    env_file:
      - ./src/sysadmin/project.env/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.${PROJECT_ENVIRONMENT_TYPE}
    networks:
      - sysadmin-network

volumes:
  static_volume:

networks:
  sysadmin-network:
